### ISSUE TITLE
Alice 下一步规划

### ISSUE THREAD

**Issue by afc163** [aliceui/aliceui.org#41]
> 迁移的 issue

@afc163:

计划在 7 月底前做完。
## 增加
- [x] #14 ~~响应式设计~~
- [x]  #12 popup 和 button-dropdown 结合的范例
- [x] #16 ~~建设 alipay-css 为 family 的支付宝专用模块库~~
- [x] #15 支付宝新版UI更新。
## spm2 支持
- [x] #2 spm2 接入，package.json格式更新，并发布到 spmjs.org
- [x] #13 静态文档托管到 spmjs.org 上 
## bugfix
- [x] tipbox 间距调整
- [x] iconfont 图标重做，解决定位不准的问题 #10
